// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kruadymtvyoclbabpagx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtydWFkeW10dnlvY2xiYWJwYWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDgxMTMsImV4cCI6MjA3MjQ4NDExM30.OrwJ4fR-AmFLUckr3AG1Zi52w30tA5jRKktCo1VKdyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});